services:
  - type: web
    name: flask-app
    env: python
    runtime: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y unzip xvfb libxi6 libgconf-2-4
      pip install -r requirements.txt
      playwright install chromium  # Ensuring Chromium is installed
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: 'true'
