services:
  - type: web
    name: selenium-app
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y wget unzip xvfb libxi6 libgconf-2-4 x11vnc && \
      wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip && \
      unzip /tmp/chromedriver.zip -d /usr/local/bin/ && \
      wget -q -O /tmp/google-chrome-stable.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
      apt-get install -y /tmp/google-chrome-stable.deb && \
      pip install -r requirements.txt
    startCommand: |
      Xvfb :99 -screen 0 1920x1080x24 & \
      x11vnc -display :99 -nopw -listen localhost -xkb & \
      export DISPLAY=:99 && gunicorn app:app